
services:
  beandfe: 
    build: .
    image: ghcr.io/boxmein/cwte2024-challenge-backend:latest 
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/cwte2024
      FLAG: 'CTE24{flag}'
      GIN_MODE: release
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cwte2024
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./seed/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ['CMD', 'pg_isready', '--username', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
volumes:
  dbdata:
