apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  name: secure-sandbox
  namespace: berg
spec:
  categories:
    - mvm
    - pwn

  difficulty: medium # Must be one of baby/easy/medium/hard/leet
  author: fabi07
  allowOutboundTraffic: false
  flag: MVM{Wh0_N33ds_S3cc0mp_4nyw4y}
  flagFormat: MVM{...}
  hideUntil:  "2025-01-25T18:00:00+00:00"
  description: |
    I love to make little games. But this time something seems to be different. If you win you might even get a flag...
  containers:
    - hostname: secure-sandbox
      image: gcr.io/mvm-x3ctf/x3ctf/challenge/secure-sandbox:latest
      environment:
        WHATEVER: VALUE
      resourceLimits:
        cpu: "0.2"
        memory: "100Mi"
      additionalCapabilities:
        - SYS_PTRACE
      ports:
        - port: 1337
          protocol: tcp # Must be either tcp/udp
          appProtocol: tcp # Signal to the frontend how to connect. For web services, use http. If unsure, use tcp.
          # Port type can be one of:
          # - publicHttpRoute: Expose this service via HTTPS with automatic HTTP to HTTPS redirection
          # - publicTlsRoute: Expose this service via a TLS-wrapped access
          # - publicPort: Expose this service on a random high port
          # - internalPort: Only expose this port for other containers, not to the public
          type: publicTlsRoute
  attachments:
    - fileName: secure-sandbox.tar.gz
      downloadUrl: /handouts/secure-sandbox.tar.gz
