apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  name: sourceless-crypto
  namespace: berg
spec:
  categories:
    - mvm
    - crypto
  difficulty: easy
  author: xtea418
  allowOutboundTraffic: false
  flag: MVM{aae30846_08b1_s0urc3less_crypt0_11ef_8010_30894a138cd3}
  flagFormat: MVM{...}
  description: |
    😇😇😇
  containers:
    - hostname: sourceless-crypto
      image: gcr.io/mvm-x3ctf/x3ctf/challenge/sourceless-crypto:latest
      environment:
        WHATEVER: VALUE
      resourceLimits:
        cpu: "0.2"
        memory: "250Mi"
      ports:
        - port: 1337
          protocol: tcp # Must be either tcp/udp
          appProtocol: tcp # Signal to the frontend how to connect. For web services, use http. If unsure, use tcp.
          # Port type can be one of:
          # - publicHttpRoute: Expose this service via HTTPS with automatic HTTP to HTTPS redirection
          # - publicTlsRoute: Expose this service via a TLS-wrapped access
          # - publicPort: Expose this service on a random high port
          # - internalPort: Only expose this port for other containers, not to the public
          type: publicTlsRoute
