apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  name: count-the-mvms
  namespace: berg
spec:
  categories:
    - misc
    - cert
  difficulty: easy # Must be one of baby/easy/medium/hard/leet
  author: shadowcone
  allowOutboundTraffic: false
  flag: x3c{th3r3_4re_9336_MVMs_1n_my_c3rtif1cat3_2931355ee608d35463f2ef7847474858}
  flagFormat: x3c{...}
  description: |
    Your task is simple: Count all occurrences of MVM in your personalized trophy. I heard AI is supreme at OCR tasks, so this should be trivial in 2025.<br/>
    <br/>
    <b>Rules:</b><br/>
    <ul>
    <li>only count MVM</li>
    <li>font does not matter</li>
    <li>MVM lookalikes should not be counted</li>
    <li>only count non-overlapping MVM</li>
    <li>you get extra brownie points if your solution finds the flag in under 5 seconds (brownie points do not affect scoring)</li>
    <li>There is a custom flag format for this challenge: x3c{th3r3_4re_[number]_MVMs_1n_my_c3rtif1cat3_[md2]} where [number] should be replaced by the decimal representation of your MVM count, and [md2] should be the MD2 representation of the string representation of the number. For example, if you found 100 MVMs in your certificate, the corresponding flag would be x3c{th3r3_4re_100_MVMs_1n_my_c3rtif1cat3_e39096f2d59363a0b177a2773ac6aa0e}.</li>
    </ul>
    <br/>
    If you are unsure whether your solution counts the correct number, kindly ask your most junior player to double check manually. It should only take a couple hours to check this number by hand.<br/>
